package com.project.app.bean

class CreditPayBean {
    var account:String = ""
    var terminal:String = ""
    var signValue:String = ""
    var backUrl:String = ""
    var noticeUrl:String = ""
    var methods:String = ""
    var pages:String = ""
    var order_number:String = ""
    var order_currency:String = ""
    var order_amount:String = ""
    var billing_firstName:String = ""
    var billing_lastName:String = ""
    var billing_email:String = ""
    var billing_phone:String = ""
    var billing_country:String = ""
    var billing_state:String = ""
    var billing_city:String = ""
    var billing_address:String = ""
    var billing_zip:String = ""
    var ship_firstName:String = ""
    var ship_lastName:String = ""
    var ship_phone:String = ""
    var ship_country:String = ""
    var ship_state:String = ""
    var ship_city:String = ""
    var ship_addr:String = ""
    var ship_zip:String = ""
    var productSku:String = ""
    var productName:String = ""
    var productNum:String = ""
}